### ISSUE TITLE
我不能编译通过，请问怎么解决

### ISSUE THREAD

**Issue by penghongquan** [puppy-rtos/stm32-zboot#1]
![image](https://github.com/puppy-rtos/stm32-zboot/assets/61901200/e435dc1d-1964-4531-98d3-be812c25289a)
报错像上面那样，谢谢

**Comment by Guozhanxin** [comment]
> ![image](https://private-user-images.githubusercontent.com/61901200/309547462-e435dc1d-1964-4531-98d3-be812c25289a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MTg1NjgsIm5iZiI6MTczMjQxODI2OCwicGF0aCI6Ii82MTkwMTIwMC8zMDk1NDc0NjItZTQzNWRjMWQtMTk2NC00NTMxLTk4ZDMtYmU4MTJjMjUyODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDAzMTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMDZhMjEzMTM2MGZiNzI0MjFkNGY1Y2ZjMDVmYmEzOGJmYmY1MjE5N2Q2NjQ0NDcyMjJhZTA2MDlkN2U1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qZG_Xiie1j87-8fTY9xFKOxH4bmbscQRzgPIzcA2Oz4) 报错像上面那样，谢谢

还不支持高版本的zig，后面再修以下
