### ISSUE TITLE
通用 STM32 BOOT 的一些建议

### ISSUE THREAD

**Issue by enkiller** [puppy-rtos/stm32-zboot#2]
不建议按照 STM32 系列各个驱动，因为 STM32 有很多系列，且每个系列下芯片众多，工作量很大。因此有如下建议：

- 使用 ARMV6 指令集编译，能够兼容所有系列。只需要一个链接脚本
- 基于 IP 核开发必要的 SPI，UART，GPIO、片内 FLASH 驱动。STM32 使用的 IP 核有限，最多不超过 3 个。
- 引脚配置信息可通过配置文件追加在 boot 的头部或尾部，来适配不同应用需求

**Comment by Guozhanxin** [comment]
改好了，目前已经支持一个bin文件跨系列了😁
